---
- name: installing remi repository
  yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present

- name: enable latest php version and install php
  yum:
    enablerepo: "remi,remi-php72"
    name: php
    state: latest

- name: Installing apache
  yum:
    name: httpd
    state: latest

- name: Enable and start apache at boot time
  systemd:
    enabled: yes
    state: started
    name: httpd

- name: Untar wordpress application
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: /var/www/html/
    extra_opts: [--strip-components=1]
    owner: apache
    group: apache
    remote_src: yes
  notify: apache restart    

- name: configuring wp-config.php file
  template:
    src: wp-config.php
    dest: /var/www/html/
    owner: apache
    group: apache
  notify: apache restart

